version: '3'

services:
  front-end:
    build: 
        context: ../.
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    build: ./database
    ports:
      - "5001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
